theme: jekyll-theme-minimal
title: Annika Tjuka's virtual bookshelf
description: 
- [Language and Mind](#language-and-mind)
- [Linguistic Theory](#linguistic-theory)
- [Theoretical Works](#theoretical-works)
- [Science as an Adventure](#science-as-an-adventure)
- [Training for Research and Teaching](#training-for-research-and-teaching)
- [Communication](#communication)
- [Inspiration](#inspiration)
